version: 0.2
env:
  variables:
    PRX_SPIRE_S3_PKG_PARAMETERS: LAMBDA_ZIP=/prx/stag/Spire/Dovetail-Counts/pkg/s3-object-key
    PRX_S3_ARCHIVE_BUILD_PATH: /app/build.zip
    PRX_BUILD_AARCH64: "true"
    PRX_CI_PUBLISH: "true"
  exported-variables:
    - PRX_SPIRE_S3_PKG_PARAMETERS
    - LAMBDA_ZIP
phases:
  build:
    commands:
      - cp env-example .env
      - docker-compose build
      - docker-compose run test
  post_build:
    commands:
      - curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/main/ci/utility/post_build.sh"
      - chmod +x post_build.sh
      - . ./post_build.sh
